destination: _site/
url: "http://127.0.0.1:4001"
baseurl: "/qumulo-doc"
port: 4001
output: pdf
print_title: Gold-Tier Hardware Servicing Guide for Qumulo
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: gold_tier_hardware_servicing_guide_sidebar
